version: '3.8'

services:
  app:
    environment:
      - DATABASE_HOST=db  # Use o nome do serviço como hostname
      - DATABASE_USER=dev_user
      - DATABASE_PASSWORD=@1971KndM!DB
      - DATABASE_NAME=dev_database
      - SECRET=dev_secret_key
  db:
    environment:
      - MYSQL_DATABASE=dev_database
      - MYSQL_USER=dev_user
      - MYSQL_PASSWORD=@1971KndM!DB
      - MYSQL_ROOT_PASSWORD=@1971KndM!DB
